//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogBookWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceDetailsTb
    {
        public int DetailsId { get; set; }
        public Nullable<int> MasterId { get; set; }
        public string Hours { get; set; }
        public Nullable<int> MenteeePersonId { get; set; }
    
        public virtual PersonTb PersonTb { get; set; }
    }
}
