//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogBookWPF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DVTEntities1 : DbContext
    {
        public DVTEntities1()
            : base("name=DVTEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AttendanceDetailsTb> AttendanceDetailsTbs { get; set; }
        public virtual DbSet<AttendanceMasterTb> AttendanceMasterTbs { get; set; }
        public virtual DbSet<PersonTb> PersonTbs { get; set; }
        public virtual DbSet<RoleTb> RoleTbs { get; set; }
    }
}
