//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogBookWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonTb
    {
        public PersonTb()
        {
            this.AttendanceDetailsTbs = new HashSet<AttendanceDetailsTb>();
            this.AttendanceMasterTbs = new HashSet<AttendanceMasterTb>();
        }
    
        public int PersonId { get; set; }
        public string Surname { get; set; }
        public string Names { get; set; }
        public string Gender { get; set; }
        public string EmailAddress { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int RoleId { get; set; }
    
        public virtual ICollection<AttendanceDetailsTb> AttendanceDetailsTbs { get; set; }
        public virtual ICollection<AttendanceMasterTb> AttendanceMasterTbs { get; set; }
        public virtual RoleTb RoleTb { get; set; }
    }
}
