//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogBookWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleTb
    {
        public RoleTb()
        {
            this.PersonTbs = new HashSet<PersonTb>();
        }
    
        public int RoleId { get; set; }
        public string Role { get; set; }
    
        public virtual ICollection<PersonTb> PersonTbs { get; set; }
    }
}
